import type { Metadata } from "next";
import "./globals.css";
import GNB from "@/components/custom/navigation/GNB";
import SNB from "@/components/custom/navigation/SNB";
import localFont from "next/font/local";

const pretendard = localFont({
  src: "../../public/fonts/Pretendard-Regular.woff2",
  display: "swap",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${pretendard.variable} ${pretendard.className}`}
    >
      <body className="w-screen h-screen p-4">
        <GNB />
        <div className="flex w-full justify-around">
          <SNB />
          <main className="w-[95%] px-2">{children}</main>
        </div>
      </body>
    </html>
  );
}
