import type { Metadata } from "next";
import "./globals.css";
import GNB from "@/components/custom/navigation/GNB";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-screen h-screen p-4">
        <GNB />
        <div>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
